### ISSUE TITLE
Missing open source license

### ISSUE THREAD

**Issue by bengregori** [StateOfCalifornia/CalCAT#10]
To fulfill the stated objectives of encouraging reuse in other jurisdictions, I recommend adding an explicit open source license to this repo.  The MIT License is the most permissive to encourage collaboration and reuse, if so inclined.

https://opensource.org/licenses/MIT

**Comment by mcstrugs** [comment]
I second this.

**Comment by kuanhulio** [comment]
```
This repository contains an application written in Shiny and for use with any US state to assist in assessing the many different models available for understanding COVID-19 transmission and spread. It brings together several data sources that are publicly available, and can be supplemented with your own data to improve the assessment.
```
I would say that gives you the ability to use this software wherever you would like to, however, I will support an MIT license on the repo itself

**Comment by kuanhulio** [comment]
@bengregori https://github.com/StateOfCalifornia/CalCAT/pull/21

👍
