### ISSUE TITLE
CSV filename is wrong in IHME data

### ISSUE THREAD

**Issue by Josteniok** [StateOfCalifornia/CalCAT#11]
The grab_ihme.R file refers to Hospitalization_all_locs.csv within the ihme-covid19.zip file. It looks like this should actually be Reference_hospitalization_all_locs.csv.

**Comment by joelrip** [comment]
Yes. Without this change, grab_ihme.R errors out with this message for me:

Error in fread(file.path(temp2, paste0(folder, "/Hospitalization_all_locs.csv"))) : 
  File '/var/folders/fv/4qk36lkx6354zf3mrgx6v9qw0000gn/T//RtmpAoIny3/file79ab300cc8c3/2020_06_24.02/Hospitalization_all_locs.csv' does not exist or is non-readable.
