### ISSUE TITLE
grab_can_county_observed_interventions Function 

### ISSUE THREAD

**Issue by AK-MCH-EPI** [StateOfCalifornia/CalCAT#12]
Working through the code to apply to Alaska and noting an issue with the grab_can_county_observed_intervention function. This appears to stem from the loop_can_cnty_observed function where the can.ca.co object returns a null. I can hard code this by specifying each fips code explicitly but the lapply function keeps failing.

Will work with it a bit to come up with my own solution but also reaching out to see if this is a simple oversight on my part.

upon further inspection it appears to be related to the RCurl::url.exists(url) code in the loop function returning false for all values.

**Comment by vargoCDPH** [comment]
have corrected  the loop_can functions to remedy this. the Rcurl:: version of the url.exists function was always returning false in some environments.

**Comment by AK-MCH-EPI** [comment]
Thanks so much, I made a similar fix to it as well on my local copy. Thanks for sharing all this work.
