### ISSUE TITLE
Highlight for nowcast map is red, which is confusing given the R-eff color scheme

### ISSUE THREAD

**Issue by adamr-hub** [StateOfCalifornia/CalCAT#2]
Highlight for nowcast map is red, which is confusing given that R-eff color scheme for the map has red as the highest R-eff category.  Shift to heavy outline to indicate county is selected?

**Comment by vargoCDPH** [comment]
agree, will work to resolve in next version

**Comment by vargoCDPH** [comment]
this issue does not apply to the open source version of CalCAT

**Comment by vargoCDPH** [comment]
###
