### ISSUE TITLE
daily updates of can_full_reff_table.csv

### ISSUE THREAD

**Issue by Bartolac** [StateOfCalifornia/CalCAT#22]
Pardon me if this is a newbie question, and I just don't know where to look.

Will the list of county-level and CA-level statistics eventually be updated daily?
It looks like they have not been updated since June 10. 
https://github.com/StateOfCalifornia/CalCAT/tree/master/data/CA

The data tables found there extend beyond that date, but it looks like those are projections.
can_state_reff_table.csv
can_full_reff_table.csv

**Comment by vargoCDPH** [comment]
We have only provided those data as demo data to run the app. The data can be updated by running the [`cal_cat_data_routine.Rmd` file](https://github.com/StateOfCalifornia/CalCAT/blob/master/cal_cat_data_routine.Rmd) for California. See the [Readme](https://github.com/StateOfCalifornia/CalCAT/blob/master/README.md) for more details.
