### ISSUE TITLE
get_epi_forecasts

### ISSUE THREAD

**Issue by samedelstein** [StateOfCalifornia/CalCAT#4]
In the grab_epi_forecasts.R file and line 106 of the Rmd file, the get_epi_forecasts function was throwing an error, saying the URL was bad. I updated to https://raw.githubusercontent.com/epiforecasts/covid-regional/master/united-states/regional-summary/rt.csv and it seems to have resolved the issue

**Comment by vargoCDPH** [comment]
thanks for getting us the updated link!
