### ISSUE TITLE
File within the GA sub-directory do not exist or are non-readable.

### ISSUE THREAD

**Issue by raviolli77** [StateOfCalifornia/CalCAT#9]
https://github.com/StateOfCalifornia/CalCAT/blob/ef1d04f3427eed65450feb7dc76c238ddd87d36b/global.R#L104

https://github.com/StateOfCalifornia/CalCAT/blob/ef1d04f3427eed65450feb7dc76c238ddd87d36b/global.R#L130

both `ygg.csv` and `ygg_county.csv` aren't available in the current data files, are these referencing `yuganggu.csv` and `yuganggu_county.csv`?

**Comment by vargoCDPH** [comment]
the naming for these files was updated in #13, we will rename the files in the provided data; however to have the freshest, you should run the markdown file for your state
